tasks:
  - name: Setup
    before: >-
      chmod ugo+w /var/run/docker.sock &&
      brew install buildpacks/tap/pack &&
      pack config pull-policy if-not-present &&
      make buildpacks-venom &&
      echo "export VENOM_VERBOSE=0" >> ~/.bashrc
    command: bash
